### ISSUE TITLE
Reduce slowly the intro song from the main screen when the user tap on Start or Continue

### ISSUE THREAD

**Issue by Jibus-** [elfketchup/EKVN#10]
This a feature request, i don't know if this can be achieved easily.

**Comment by elfketchup** [comment]
It was achieved in about 30 minutes with some Cocos2D / SimpleAudioEngine knowledge. ;-)

To enable this, just add "fade out time in seconds" to the file "main_menu.plist" and make sure the Type is set to "Number." (the default value is for this is 1.0, but change it to whatever seems best to you... I'd probably switch it to 0.5 for a faster transition) To disable the feature, just delete it from the property list file, and the main menu will go back to the "old" way of instantly stopping the music and loading the scene.

Also I added a fade-out/fade-to-black effect, since it looked weird and kind of annoying to tap the button, and hear the music fade, but not see anything happening on the screen. That gradual fade-to-black effect gives users something to look at. :-P

**Comment by Jibus-** [comment]
Thanks you very much !
