### ISSUE TITLE
Background image for the text action in the welcome screen

### ISSUE THREAD

**Issue by Jibus-** [elfketchup/EKVN#12]
At this time, its possible to control the size and the font of the action text in the welcome screen (start, resume...).

It would be convenient if we can add a background to this title.

Thanks again for your work and for your time.

**Comment by elfketchup** [comment]
Do you mean putting a background image behind the text for "New Game" and "Continue"? If you're familiar with Cocos2D, you could very easily add this yourself. For example, adding a background image behind "New Game" is as simple as:

```// "playLabel" is the name of the CCSpriteTTF object that stores text data for "New Game"
CCSprite* playLabelBG = [CCSprite spriteWithImageNamed:@"some_image.png"];
playLabelBG.position = playLabel.position;
[self addChild:playLabelBG z:(playLabel.zOrder - 1)];```

If you're not familiar with Cocos2D... well, that's fine too, since I added the functionality anyways. In the file "main_menu.plist", you can edit the values for "startnewgame background image" and "continue background image" and put in the name of the image file you want to use.

**Comment by Jibus-** [comment]
As always, thanks for your time and your work :)

Does this mean that we add, like the other UI images, to make one image per device ?

**Comment by elfketchup** [comment]
With Cocos2D, you would need at three images total if you plan to make a Universal app:

1. For Retina-Display iPhone (4 to 5S)
2. For non-Retina-Display iPad (iPad 1, iPad 2, iPad Mini)
3. For Retina-Display iPad (iPad 3 and newer, iPad Mini 2 and newer)

I don't think Apple still requires people to support non-Retina iPhones (3GS and older), though you could still make one if you really want to. And Cocos2D still doesn't officially support Retina-HD (iPhone 6 and 6 Plus).

**Comment by Jibus-** [comment]
Ok, thanks you again !
