### ISSUE TITLE
Feature : ability to define a speechbox image

### ISSUE THREAD

**Issue by Jibus-** [elfketchup/EKVN#15]
It would be convenient to have the ability to define a speechbox like we define a background (ie : .SPEECHBOX:cinematic_speech.png)

My user case is that i would like to set a different speechbox for "cinematic" mode.

**Comment by elfketchup** [comment]
There's now a .SETSPEECHBOX command, the syntax is:

.SETSPEECHBOX:(filename for image):(duration of switch from old image to new image)

The duration parameter is optional, and has a default value of 0 seconds (meaning it's instant unless specified otherwise). Also, you should make sure that the images are the same size, or things will look very strange.

**Comment by Jibus-** [comment]
Thanks you as always for your prompt response and work !
