### ISSUE TITLE
Feature : abiliy to set X and Y position of the choicebox

### ISSUE THREAD

**Issue by Jibus-** [elfketchup/EKVN#17]
It would be convenient to have the ability to set the position of the choicebox (center by default) like "New Game" et "Continue" label from the main settings plist.

**Comment by elfketchup** [comment]
You can now edit "vnscene view settings.plist" and add the fields:

choicebox offset x
choicebox offset y

to do this. (The latest version of this file has them included already). By default, both fields are set to zero, which means the buttons appear in the center area of the screen like usual, but you can adjust these values to move them along the X/Y axis by a certain number of points.

There's also a .MODIFYCHOICEBOXOFFSET script command to do this while the script is running, in case you wanted to change the buttons position (though I don't recommend changing it often since it will confuse -- or at least annoy -- players).

**Comment by Jibus-** [comment]
Excellent work perfectly

Thanks you !
