### ISSUE TITLE
Feature : .PLAYMUSIC:nil stop gracefully

### ISSUE THREAD

**Issue by Jibus-** [elfketchup/EKVN#19]
As the opening, it woult be great if the playmusic:nil command stop the music "gracefully"

**Comment by elfketchup** [comment]
.PLAYMUSIC has now been changed to have fade-in/fade-out. The full syntax for the command is:

.PLAYMUSIC:(nil or filename):(loop):(fade-in/fade-out time in seconds)

So to play background music that loops and has no fade-in, you would write:

.PLAYMUSIC:music.mp3:YES:0

And to just stop the music with fade-in, you could write:

.PLAYMUSIC:nil

…just the same as before. (loop and fade duration are optional)

Also, I don't remember if I've mentioned this to you before, but if you're seriously building a visual novel, have you looked at [Ren'Py](http://www.renpy.org) or [TyranoBuilder](http://tyranobuilder.com)? Both of them officially support iOS… as well as Android and PC/Mac/Linux (and in the case of TyranoBuilder, HTML5 as well). 

Ren'Py is free and has a large user base, while TyranoBuilder costs about $14 on Steam but doesn't require any programming knowledge, and has a visual editor (much like Interface Builder in Xcode) so you can see everything laid out visually.

I'm bringing this up now because Apple's WWDC event is coming up next month. This means a new version of iOS, which could cause compatibility issues with Cocos2D. While I imagine that the Cocos2D devs will eventually release an update to fix any such issues, it will probably take a while… for an example of this, keep in mind that Cocos2D STILL does not support the iPhone 6's Retina HD, even several months after the iPhone 6's release.

This means that any game built on Cocos2D (such any visual novels made with EKVN) could run into issues and bugs when iOS 9 comes out, and there's no telling when any fixes will be provided.

Additionally, this could become more of a problem if the next version of Cocos2D is the rumored "version 4" which is supposed to make many changes and restructure how Cocos2D works. If you ask why this is a problem, it's because I probably won't update EKVN when the next major release of Cocos2D comes out.

There are two reasons for this. First, is that even people on Cocos2D's official forum will admit that less and less developers are using Cocos2D. More people are using cross-platform tools like Unity, so that they can release on iOS and Android at the same time (and possibly on Steam too).

The second reason is that EKVN was created back when there were no visual novel frameworks for iOS, but now that Ren'Py and TyranoBuilder support iOS, EKVN is obsolete. There's no point updating software when there are much better alternatives that exist.

If EKVN meets your needs for now, that's good. But with cross-platform development tools becoming more popular, new versions of iOS potentially breaking things each year, and Cocos2D itself slowly becoming obsolete, EKVN itself will eventually not be able to keep up, and someday it will just be too old and too simple for making visual novels for iOS.

Anyways, I just wanted to point this out to you now. You're certainly free to do whatever you believe is best, but if you really want to make a good visual novel and not worry about whether or not it will run on the latest version of iOS, you might want to consider something more reliable.

**Comment by Jibus-** [comment]
I am very appreciate your comment.

When I began my project, I looked into Ren'Py but there wasn't support of iOS yet and i tought it will take months for the support of iOS. So I decided to use your framework first.

I plan to release the app this month (hopefully...). Your framework does everything I need. But of course, it would be wise to move to another solution such as Ren'Py, which, as you said, support now iOS and  Android. So in the next few month, i will move to this solution.

The only concern for me is the support of iphone 6 / 6 plus. I already prepared images with the right format. I planned to hack cocos2d to make this work. Hopefully again, i hope this will work :)

Thanks you again for all your work and for your time.
