### ISSUE TITLE
iPhone 6 & iPhone6Plus assets

### ISSUE THREAD

**Issue by Jibus-** [elfketchup/EKVN#21]
Hello,

We talk about this a few month ago about the assets for iphone 6/6+ devices. 
I have assets ready to : 
iphone 6 : 1334 x 750
iphone 6 plus : 2208 x 1242

Unfortunatly, i couldn't find a good hack on cocos2d forums (the project is on 3.3). So i tryed the new version (3.4) with spritebuilder, but it seems that there is not a good support.

I am planning to submit my app to Apple in the next few days. So do you think that Apple will accept an app with streched images. If not, do you think it's complicated to add a new extension like -iphone6 and -iphone6plus asset ?

Thanks for your answer

**Comment by elfketchup** [comment]
You would probably get better (and more accurate) answers if you ask this on the cocos2D forums, but I would like to think that Apple will accept your app. 

The reason for this is that people still make games using cocos2D and submit them to Apple. I assume Apple does accept them, since if cocos2d games kept getting rejected just because they didn't have Retina-HD support, there would be many, many more people complaining on the cocos2D forums about this. As it is, the forums are (relatively) peaceful.

As for how difficult it is to add new extensions... considering that the "hacks" that people use to add iPhone 6/6+ support never become popular (and the ones I've seen have bugs), and the official cocos2D dev team doesn't release any official fix (despite having multiple programmers), I can only assume that there's no easy fix.

**Comment by Jibus-** [comment]
Thanks you for your answer
